# coding: utf-8

"""
    This class is auto generated from the Infobip OpenAPI specification
    through the OpenAPI Specification Client API libraries (Re)Generator (OSCAR),
    powered by the OpenAPI Generator (https://openapi-generator.tech).
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictFloat, StrictStr


class MmsPrice(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    price_per_message: Optional[StrictFloat] = Field(
        None, alias="pricePerMessage", description="Price per one MMS."
    )
    currency: Optional[StrictStr] = Field(
        None, description="The currency in which the price is expressed."
    )
    __properties = ["pricePerMessage", "currency"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MmsPrice:
        """Create an instance of MmsPrice from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MmsPrice:
        """Create an instance of MmsPrice from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return MmsPrice.parse_obj(obj)

        _obj = MmsPrice.parse_obj(
            {
                "price_per_message": obj.get("pricePerMessage"),
                "currency": obj.get("currency"),
            }
        )
        return _obj
