# coding: utf-8

"""
    This class is auto generated from the Infobip OpenAPI specification
    through the OpenAPI Specification Client API libraries (Re)Generator (OSCAR),
    powered by the OpenAPI Generator (https://openapi-generator.tech).
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from pydantic import BaseModel, Field, StrictStr


class MmsWebhookInboundMessageSegmentText(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    content_type: StrictStr = Field(
        ...,
        alias="contentType",
        description="Content type of the message segment, e.g. `text/plain`.",
    )
    value: StrictStr = Field(..., description="Message text.")
    __properties = ["contentType", "value"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MmsWebhookInboundMessageSegmentText:
        """Create an instance of MmsWebhookInboundMessageSegmentText from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MmsWebhookInboundMessageSegmentText:
        """Create an instance of MmsWebhookInboundMessageSegmentText from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return MmsWebhookInboundMessageSegmentText.parse_obj(obj)

        _obj = MmsWebhookInboundMessageSegmentText.parse_obj(
            {"content_type": obj.get("contentType"), "value": obj.get("value")}
        )
        return _obj
