# coding: utf-8

"""
    This class is auto generated from the Infobip OpenAPI specification
    through the OpenAPI Specification Client API libraries (Re)Generator (OSCAR),
    powered by the OpenAPI Generator (https://openapi-generator.tech).
"""


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictStr

from infobip.models.sms_status import SmsStatus


class SmsResponseDetails(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    message_id: Optional[StrictStr] = Field(
        None,
        alias="messageId",
        description="Unique message ID. If not passed, it will be automatically generated and returned in a response.",
    )
    status: Optional[SmsStatus] = None
    to: Optional[StrictStr] = Field(
        None, description="The destination address of the message."
    )
    __properties = ["messageId", "status", "to"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SmsResponseDetails:
        """Create an instance of SmsResponseDetails from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of status
        if self.status:
            _dict["status"] = self.status.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SmsResponseDetails:
        """Create an instance of SmsResponseDetails from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return SmsResponseDetails.parse_obj(obj)

        _obj = SmsResponseDetails.parse_obj(
            {
                "message_id": obj.get("messageId"),
                "status": SmsStatus.from_dict(obj.get("status"))
                if obj.get("status") is not None
                else None,
                "to": obj.get("to"),
            }
        )
        return _obj
