# coding: utf-8

"""
    This class is auto generated from the Infobip OpenAPI specification
    through the OpenAPI Specification Client API libraries (Re)Generator (OSCAR),
    powered by the OpenAPI Generator (https://openapi-generator.tech).
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from pydantic import BaseModel, Field, StrictStr, validator
from models.numbers_mo_non_forward_action import (
    NumbersMoNonForwardAction,
)


class NumbersBlockAction(NumbersMoNonForwardAction):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    block_type: StrictStr = Field(..., alias="blockType", description="Block type.")
    __properties = ["type", "editable", "blockType"]

    @validator("block_type")
    def block_type_validate_enum(cls, v):
        if v not in ("FROM_ANY_SENDER", "FROM_SENDER"):
            raise ValueError(
                "must validate the enum values ('FROM_ANY_SENDER', 'FROM_SENDER')"
            )
        return v

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> NumbersBlockAction:
        """Create an instance of NumbersBlockAction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> NumbersBlockAction:
        """Create an instance of NumbersBlockAction from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return NumbersBlockAction.parse_obj(obj)

        _obj = NumbersBlockAction.parse_obj(
            {
                "type": obj.get("type"),
                "editable": obj.get("editable"),
                "block_type": obj.get("blockType"),
            }
        )
        return _obj
