# coding: utf-8

"""
    This class is auto generated from the Infobip OpenAPI specification
    through the OpenAPI Specification Client API libraries (Re)Generator (OSCAR),
    powered by the OpenAPI Generator (https://openapi-generator.tech).
"""


from __future__ import annotations
from inspect import getfullargspec
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr


class SmsIndiaDltOptions(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    content_template_id: Optional[StrictStr] = Field(
        None,
        alias="contentTemplateId",
        description="Registered DLT content template ID which matches message you are sending.",
    )
    principal_entity_id: StrictStr = Field(
        ...,
        alias="principalEntityId",
        description="Your assigned DLT principal entity ID.",
    )
    __properties = ["contentTemplateId", "principalEntityId"]

    class Config:
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SmsIndiaDltOptions:
        """Create an instance of SmsIndiaDltOptions from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SmsIndiaDltOptions:
        """Create an instance of SmsIndiaDltOptions from a dict"""
        if obj is None:
            return None

        if type(obj) is not dict:
            return SmsIndiaDltOptions.parse_obj(obj)

        _obj = SmsIndiaDltOptions.parse_obj(
            {
                "content_template_id": obj.get("contentTemplateId"),
                "principal_entity_id": obj.get("principalEntityId"),
            }
        )
        return _obj
